apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/temporal:1.6.2
          imagePullPolicy: IfNotPresent
          command: [temporal, server, start-dev, --ip, 0.0.0.0]
          ports:
            - name: grpc
              containerPort: 7233
          startupProbe:
            tcpSocket:
              port: grpc
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: grpc
            periodSeconds: 2
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "4"
              memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  selector:
    app: temporal
  ports:
    - name: grpc
      port: 7233
      targetPort: grpc
